export const CATEGORIES = {
    "F&B": "",
    "Grocery": "",
    "Pizza": "",
    "Chicken": "",
    "Dhokla": "",
    "Idli": "",
    "Cleaning & Household": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/CleaningHousehold.png",
    "Snacks and Namkeen": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/SnacksandNamkeen.png",
    "Fruit Juices and Fruit Drinks": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/FruitJuicesFruitDrinks.png",
    "Pasta, Soup and Noodles": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Pasta,SoupandNoodles.png",
    "Masala & Seasoning": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Masala&Seasoning.png",
    "Bakery, Cakes & Dairy": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/BakeryCakesDairy.png",
    "Snacks, Dry Fruits, Nuts": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Snacks,DryFruits,Nuts.png",
    "Oil & Ghee": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Oil&Ghee.png",
    "Atta, Flours and Sooji": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/AttaFloursSooji.png",
    "Rice and Rice Products": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/RiceandRiceProducts.png",
    "Snacks & Branded Foods": "",
    "Beverages": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Beverages.png",
    "Gourmet & World Foods": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Gourmet&WorldFoods.png",
    "Sauces, Spreads and Dips": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Sauces,SpreadsandDips.png",
    "Frozen Vegetables": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/FrozenVegetables.png",
    "Chocolates and Biscuits": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/ChocolatesBiscuits.png",
    "Beauty & Hygiene": "",
    "Foodgrains": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Foodgrains.png",
    "Dals and Pulses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/DalsPulses.png",
    "Tea and Coffee": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Teaandcoffee.png",
    "Fruits and Vegetables": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/FruitsVegetables.png",
    "Energy and Soft Drinks": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/EnergyandSoftDrinks.png",
    "Pickles and Chutney": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/PicklesandChutney.png",
    "Salt, Sugar and Jaggery": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Salt,SugarandJaggery.png",
    "Eggs, Meat & Fish": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/EggsMeatFish.png",
    "Frozen Snacks": "https://d2v00mt5yqy11h.cloudfront.net/categories/grocery.png",
    "Ready to Cook and Eat": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/ReadytoCookandEat.png",
    "Cereals and Breakfast": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/CerealsBreakfast.png",
    "Gift Voucher": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/GiftVoucher.png",
    "Pet Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/PetCare.png",
    "Desktop and Laptop": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/DesktopandLaptop.png",
    "Cooking and Baking Needs": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/CookingBakingNeeds.png",
    "Tinned and Processed Food": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/TinnedandProcessedFood.png",
    "Baby Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/BabyCare.png",
    "Water": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/Water.png",
    "Hair Care - Shampoo, Oils, Conditioners": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/HairCare-Shampoo,Oils,Conditioners.png",
    "Kitchen Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/KitchenAccessories.png",
    "Hand Wash": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/HandWash.png",
    "Stationery": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/Stationery.png",
    "Dairy and Cheese": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/DairyCheese.png",
    "Indian Sweets": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/IndianSweets.png",
    "Clothing Sets": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/ClothingSets.png",
    "Tops": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Tops.png",
    "Dresses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Dresses.png",
    "Shorts": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Shorts.png",
    "Sweaters": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Sweaters.png",
    "Formal Shoes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/FormalShoes.png",
    "Kurtas & Kurta Sets": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Kurtas&KurtaSets.png",
    "Swimwear": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Swimwear.png",
    "T Shirts": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/TShirts.png",
    "Work & Safety Shoes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Work&SafetyShoes.png",
    "Shirts": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Shirts.png",
    "Handbags": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Handbags.png",
    "Sarees": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Briefs": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Briefs.png",
    "Belts": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Belts.png",
    "Trousers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Trousers.png",
    "Unstitched Fabrics": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/UnstitchedFabrics.png",
    "Earrings": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Earrings.png",
    "Coordinates": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Coordinates.png",
    "Rings": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Backpacks": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Backpacks.png",
    "Innerwear & Sleepwear": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/InnerwearSleepwear.png",
    "Jumpsuits": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Jumpsuits.png",
    "Kurtis, Tunics": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Kurtis,Tunics.png",
    "Heels": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Heels.png",
    "Jewellery Sets": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/JewellerySets.png",
    "Necklaces": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Necklaces.png",
    "Pendants": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Pendants.png",
    "Jackets & Coats": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Jackets&Coats.png",
    "Trolley, Luggage & Suitcases": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Trolley,Luggage&Suitcases.png",
    "Lehenga Cholis": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/LehengaCholi.png",
    "Bracelets": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Bracelets.png",
    "Watches": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Nightwear & Loungewear": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Nightwear&Loungewear.png",
    "Sandals & Floaters": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Sandals&Floaters.png",
    "Flip-Flops & Flats": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Eye Glass Frames": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/EyeGlassFrames.png",
    "Track Pants": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Skirts": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Skirts.png",
    "Palazzos": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Palazzos.png",
    "Bangles & Bracelets": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/BanglesBracelets.png",
    "Casual Shoes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/CasualShoes.png",
    "Sunglasses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Sunglasses.png",
    "Suits": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Suits.png",
    "Dupattas & Shawls": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/DupattasShawls.png",
    "Blazers & Waistcoats": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/BlazersWaistcoats.png",
    "Blouses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Blouse.png",
    "Sweatshirts": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Sweatshirts.png",
    "Chains": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Chains.png",
    "Lingerie Sets & Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/LingerieSetsAccessories.png",
    "Sleepwear & Loungewear": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/InnerwearSleepwear.png",
    "Sports Shoes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/SportsShoes.png",
    "Socks": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Socks.png",
    "Jeans": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Jeans.png",
    "Ethnic Wear": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/EthnicWear.png",
    "Bra": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Bra.png",
    "Anklets": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Anklets.png",
    "Night Suits": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/NightSuits.png",
    "Tights, Leggings & Jeggings": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Tights,Leggings&Jeggings.png",
    "Boots": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Boots.png",
    "Eye Glasses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/EyeGlasses.png",
    "Gloves": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Gloves.png",
    "Party Wear": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/PartyWear.png",
    "Boxers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Boxers.png",
    "Shapewear": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Joggers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Joggers.png",
    "Towels": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Towels.png",
    "Mangalsutra": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Mangalsutra.png",
    "Microfiber Wipes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/MicrofiberWipes.png",
    "T shirt for women": "",
    "Vests": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Vests.png",
    "Home Decor": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/HomeDecor.png",
    "Kitchen Tools": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/KitchenTools.png",
    "Serveware": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/Serveware.png",
    "Garden & Outdoor": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/GardenOutdoor.png",
    "Kitchen Storage and Containers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/KitchenStorageandContainers.png",
    "Home Furnishing - Bedding and Linen": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/HomeFurnishing-BeddingandLinen.png",
    "Toys and Games": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/ToysandGames.png",
    "Electricals": "https://d2v00mt5yqy11h.cloudfront.net/categories/home_decor.png",
    "Cleaning Supplies": "https://d2v00mt5yqy11h.cloudfront.net/categories/home_decor.png",
    "Sports and Fitness Equipment": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/SportsandFitnessEquipment.png",
    "Cookware": "https://d2v00mt5yqy11h.cloudfront.net/categories/home_decor.png",
    "Furniture": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HomeDecor/Furniture.png",
    "Bathroom and Kitchen fixtures": "https://d2v00mt5yqy11h.cloudfront.net/categories/home_decor.png",
    "Pooja Needs": "",
    "Lighting & Electric Fans": "",
    "Disposables and Garbage Bags": "",
    "Kitchen Appliances": "",
    "Closet/Laundry/Shoe Organization": "https://d2v00mt5yqy11h.cloudfront.net/categories/home_decor.png",
    "Storage and Organisation": "",
    "Women's Fashion Accessories": "",
    "Nutrition and Fitness Supplements": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/NutritionandFitnessSupplements.png",
    "Medicated Skin Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/MedicatedSkinCare.png",
    "Pain Relief": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/PainRelief.png",
    "Sexual Wellness": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/SexualWellness.png",
    "Cold and Cough": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/ColdCough.png",
    "Speciality Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/SpecialityCare.png",
    "Healthcare & Fitness Devices": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/Healthcare&FitnessDevices.png",
    "Oral Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/OralCare.png",
    "Health and Safety": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/HealthandSafety.png",
    "Medicated Hair Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/MedicatedHairCare.png",
    "Feminine Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/FeminineCare.png",
    "Health Foods and Drinks": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/HealthFoodsandDrinks.png",
    "Gastric Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/GastricCare.png",
    "Eye Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/EyeCare.png",
    "Ayurvedic": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/Ayurvedic.png",
    "Wound Care and Dressings": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/WoundCareandDressings.png",
    "ENT Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/ENTCare.png",
    "Elder Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/ElderCare.png",
    "Diabetes Control": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/DiabetesControl.png",
    "Covid Essentials": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/CovidEssentials.png",
    "Orthopaedic Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/OrthopaedicCare.png",
    "Sanitizers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/Sanitizers.png",
    "Mental Wellness": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/MentalWellness.png",
    "Baby Care - Diapers and Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/BabyCareDiapersAccessories.png",
    "Mobility Aids": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/MobilityAids.png",
    "Maternity Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/MaternityCare.png",
    "Baby Care - Rash Creams": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/BabyCareRashCreams.png",
    "Contraceptives": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/Contraceptives.png",
    "Surgicals": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/Surgicals.png",
    "Skin Care - Lotions, Moisturisers, and Creams": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/SkinCare-Lotions,Moisturisers,andCreams.png",
    "Bath Soaps and Gels": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/BathSoapsGels.png",
    "Makeup - Lips": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-Lips.png",
    "Hair Oils, Care, and Styling": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/HairOils,Care,andStyling.png",
    "Fragrance": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Fragrance.png",
    "Skin Care - Face Cleansers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/SkinCare-FaceCleansers.png",
    "Grooming Tools and Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/GroomingToolsAccessories.png",
    "Shaving and Grooming": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/ShavingandGrooming.png",
    "Skin Care - Oils and Serums": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/SkinCare-OilsandSerums.png",
    "Makeup - Kits and Combos": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-KitsandCombos.png",
    "Skin Care - Hand and Feet": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/SkinCare-HandandFeet.png",
    "Body Care - Bath Salt and Additives": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/BodyCareBathSaltAdditives.png",
    "Shampoos and Conditioners": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/ShampoosandConditioners.png",
    "Body Care - Cleansers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/BodyCareCleansers.png",
    "Body Care - Moisturizers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/BodyCareMoisturizers.png",
    "Makeup - Face": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-Face.png",
    "Sexual Wellness & Sensuality": "",
    "Makeup - Nail Care": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-NailCare.png",
    "Baby care ": "",
    "Beard Care and Tools": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/BeardCareTools.png",
    "Body Care - Loofah and Other Tools": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/BodyCareLoofahOtherTools.png",
    "Bath & Body": "",
    "Makeup - Eyes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-Eyes.png",
    "Makeup - Sets and Kits": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-SetsandKits.png",
    "Makeup - Tools and Brushes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-ToolsandBrushes.png",
    "Skin Care": "",
    "Mobile Cover": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/MobileCover.png",
    "Headset": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Headset.png",
    "Mobile Phone": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/MobilePhon.png",
    "Computer Component": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/ComputerComponent.png",
    "Speaker": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Speaker.png",
    "Networking Device": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/NetworkingDevice.png",
    "Laptop Skin": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/LaptopSkin.png",
    "Laptop Bag": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/LaptopBag.png",
    "Remote": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Remote.png",
    "Smart Lighting": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/SmartLightning.png",
    "Charger": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Charger.png",
    "Camera Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/CameraAccessories.png",
    "TV Remote": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/TVRemote.png",
    "Audio Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/AudioAccessories.png",
    "Adapter": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Adapter.png",
    "Storage Drive": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/StorageDrive.png",
    "Mousepad": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Mousepad.png",
    "Extension Cord": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/ExtensionCord.png",
    "Laptop Stand": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/LaptopStand.png",
    "Camera Bag": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/CameraBag.png",
    "Gaming Controller": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/GamingController.png",
    "Computer Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/ComputerAccessories.png",
    "Mobile Screen Guard": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/MobileScreenGuard.png",
    "Earphone": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Earphone.png",
    "Batteries": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Batteries.png",
    "Mobile Accessories": "",
    "Printer Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/PrinterAccessories.png",
    "Mouse": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Mouse.png",
    "Computer Peripheral": "",
    "Screen Protector": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/ScreenProtector.png",
    "Cable": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Cable.png",
    "Camera": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Camera.png",
    "Laptop": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Laptop.png",
    "Smart Watch": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/SmartWatch.png",
    "Headphone": "",
    "Home Safe": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/HomeSafe.png",
    "Power Bank": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/PowerBank.png",
    "Pen Drive": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/StorageDrive.png",
    "Video Games": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/VideoGames.png",
    "TV Mount": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/TVMount.png",
    "Gaming": "",
    "Biometrics": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Biometrics.png",
    "Mobile Mount": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/MobileMount.png",
    "Cooling Pad": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/CoolingPad.png",
    "Health, Home and Personal Care": "",
    "Microphone": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Microphone.png",
    "Video Player Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/VideoPlayerAccessories.png",
    "Wearable Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/WearableAccessories.png",
    "Camera Lens": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/CameraLens.png",
    "Memory Card": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/MemoryCard.png",
    "Shaver": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Shaver.png",
    "Standard TV": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/StandardTV.png",
    "Streaming Device": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/StreamingDevice.png",
    "TV Stand": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/TVStand.png",
    "Tablet": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Tablet.png",
    "Toaster": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Toaster.png",
    "Trimmer": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Trimmer.png",
    "True Wireless Stereo (TWS)": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/TrueWirelessStereo(TWS).png",
    "Vehicle Audio": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/VehicleAudio.png",
    "Dehumidifier": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Dehumidifier.png",
    "Juicer": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Juicer.png",
    "Air Heater": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/AirHeater.png",
    "Blender": "https://d2v00mt5yqy11h.cloudfront.net/categories/appliances.png",
    "Humidifier": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Humidifier.png",
    "Air Purifier": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/AirPurifier.png",
    "Air Cleaner Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/AirCleanerAccessories.png",
    "Air Conditioner": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/AirConditioner.png",
    "Air Conditioner Accessories": "https://d2v00mt5yqy11h.cloudfront.net/categories/appliances.png",
    "Air Cooler": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/AirCooler.png",
    "Epilator": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Epilator.png",
    "Hair Straightener": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/HairStraightener.png",
    "Hair Dryer": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/HairDryer.png",
    "Hair Curler": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/HairCurler.png",
    "Hair Crimper": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/HairCrimper.png",
    "Electric Brush": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/ElectricBrush.png",
    "Electric Iron": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/ElectricIron.png",
    "Electric Sewing Machine": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/ElectricSewingMachine.png",
    "Water Heater": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterHeater.png",
    "Heater Cables": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/HeaterCables.png",
    "Coffee Maker": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/CoffeeMaker.png",
    "Beverage Maker": "https://d2v00mt5yqy11h.cloudfront.net/categories/appliances.png",
    "Roti Maker": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/RotiMaker.png",
    "Induction Cooktop": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/InductionCooktop.png",
    "Sandwich Maker": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/SandwichMaker.png",
    "Electric Cooker": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/ElectricCooker.png",
    "Electric Kettle": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/ElectricKettle.png",
    "Microwave Oven": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/MicrowaveOven.png",
    "OTG": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/OTG.png",
    "Electric Air Fryer": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/ElectricAirFryer.png",
    "Cooking Appliance Accessories ": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/CookingApplianceAccessories.png",
    "Coffee Grinder": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/CoffeeGrinder.png",
    "Food Processor": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/FoodProcessor.png",
    "Pasta Maker": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/PastaMaker.png",
    "Food Processor Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/FoodProcessorAccessories.png",
    "Mixer Grinder": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/MixerGrinder.png",
    "Wet Grinder": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WetGrinder.png",
    "Dishwasher": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Dishwasher.png",
    "Dishwasher Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/DishwasherAccessories.png",
    "Electric Chimney": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/ElectricChimney.png",
    "Freezer": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Freezer.png",
    "Refrigerator": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Refrigerator.png",
    "Refrigerator Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/RefrigeratorAccessories.png",
    "Vacuum Cleaner": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/VacuumCleaner.png",
    "Vacuum Cleaner Parts and Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/VacuumCleanerPartsandAccessories.png",
    "Washing Machine": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WashingMachine.png",
    "Washing Machine Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WashingMachineAccessories.png",
    "Water Purifier": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterPurifier.png",
    "Water Cooler": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterCooler.png",
    "Water Dispenser": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterDispenser.png",
    "Water Purifier Service Kit": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterPurifierServiceKit.png",
    "Water Purifier Filter": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterPurifierFilter.png",
    "Water Purifier Candle": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterPurifierCandle.png",
    "Water Purifier Pipe": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterPurifierPipe.png",
    "Water Purifier Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterPurifierAccessories.png",
    "Water Cooler Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/WaterCoolerAccessories.png",
    "Inverter": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/Invertor.png",
    "Inverter Batteries": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/InverterBatteries.png",
    "Battery tray": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Grocery/BatteryTray.png",
    "Voltage Stabilizer": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Appliances/VoltageStabilizer.png",
    "Makeup - Body": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-Body.png",
    "Makeup - Remover": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/BPC/Makeup-Remover.png",
    "Sherwanis": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Sherwanis.png",
    "Track Shirts": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/TrackShirts.png",
    "Track Suits": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/TrackSuits.png",
    "Capris": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Capris.png",
    "Playsuits": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Playsuits.png",
    "Shrugs & Blouses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/shrugsforwomen.png",
    "Dhotis & Dhoti Pants": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/DhotisDhotiPants.png",
    "Churidars": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Churidars.png",
    "Salwars": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Salwars.png",
    "Dungarees & Jumpsuits": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/DungareesJumpsuits.png",
    "Caps & Hats": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/CapsHats.png",
    "Dress Materials": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Burqas & Hijabs": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/BurqasHijabs.png",
    "Blouse Pieces": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/BlousePieces.png",
    "Robes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Robes.png",
    "Thermal Wear": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/ThermalWear.png",
    "Swim Bottoms": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/SwimBottms.png",
    "Camisoles": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Camisoles.png",
    "Bath Robes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/BathRobes.png",
    "Pyjamas": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Pyjamas.png",
    "Stockings": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Stockings.png",
    "Laces": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Laces.png",
    "Soles & Charms": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Shoe Racks & Organisers": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
    "Shoe Care - Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/ShoeCare-Accessories.png",
    "Outdoor Shoes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/OutdoorShoes.png",
    "Ethnic Shoes": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/EthnicShoes.png",
    "Contact Lenses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/ContactLensCases.png",
    "Contact Lens Cases": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/ContactLensCases.png",
    "Contact Lens Solutions": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/ContactLensSolutions.png",
    "Contact Lens Tweezers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/ContactLensTweezers.png",
    "Eyeglasses Pouches & Cases": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/EyeglassesPouchesCases.png",
    "Eyewear Slings": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/EyewearSlings.png",
    "Nosepins & Noserings": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Nosepins.png",
    "Toe Rings": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/ToeRings.png",
    "Gold Coins": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/GoldCoin.png",
    "Brooch": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/Brooch.png",
    "Desktop": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Desktop.png",
    "Keyboard": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Keyboard.png",
    "Monitor": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Monitor.png",
    "Home Audio": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/HomeAudio.png",
    "Camcorder": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Camcorder.png",
    "Photo Printer": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/PhotoPrinter.png",
    "Tripod": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Tripod.png",
    "UPS": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/UPS.png",
    "Printer": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Printer.png",
    "Docking Station": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/DockingStation.png",
    "Keyboard Guard": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/KeyboardGuard.png",
    "Computer Software": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/ComputerSoftware.png",
    "Ebook Reader": "https://d2v00mt5yqy11h.cloudfront.net/categories/health_wellness.png",
    "Tablet Accessories ": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/TabletAccessories.png",
    "Gaming Chair": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/GamingChair.png",
    "Gaming Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/GamingAccessories.png",
    "Gaming Console": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/GamingConsole.png",
    "Selfie Stick": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/SelfieStick.png",
    "Mobile Skin Sticker": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/MobileSkinSticker.png",
    "Home Alarm": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/HomeAlarm.png",
    "Home Automation": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/HomeAutomation.png",
    "Smart Switch": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/SmartWatch.png",
    "Intercom": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Intercom.png",
    "Sensor": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Sensor.png",
    "Smart TV": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/SmartTV.png",
    "TV Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/TVAccessories.png",
    "Virtual Reality Headset": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/VirtualRealityHeadset.png",
    "3D Glasses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/3DGlasses.png",
    "3D Modulator": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/3DModulator.png",
    "Projector": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Projector.png",
    "Projector Screen": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/ProjectorScreen.png",
    "Projector Mount": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/ProjectorMount.png",
    "Projector Accessories": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/ProjectorAccessories.png",
    "TV Part": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/TVPart.png",
    "Set Top Box": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/SetTopBox.png",
    "Video Player": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/VideoPlayer.png",
    "Digital Photo Frame": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/DigitalPhotoFrame.png",
    "Home Theatre Projector": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/HomeTheatreProjector.png",
    "Smart Band": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/SmartBand.png",
    "Smart Glasses": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/SmartGlasses.png",
    "Watch Strap Band": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/WatchStrapBand.png",
    "Homeopathy": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/Homeopathy.png",
    "Unani and Siddha": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/UnaniandSiddha.png",
    "Speciality Face Cleansers": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/SpecialityFaceCleansers.png",
    "Nursing and Feeding": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/NursingandFeeding.png",
    "Baby Care - Wipes and Buds": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/HealthWellness/BabyCareWipesandBuds.png",
    "Breathe Easy": "https://d2v00mt5yqy11h.cloudfront.net/categories/health_wellness.png"
  }