export const CATEGORIES = {
  "F&B": "",
  "Dhokla": "",
  "Idli": "",
  "Cleaning & Household": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cleaning%20&%20Household.png",
  "Snacks and Namkeen": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Snacks%20and%20Namkeen.png",
  "Fruit Juices and Fruit Drinks": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Fruit%20Juices%20and%20Fruit%20Drinks.png",
  "Pasta, Soup and Noodles": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Pasta,%20Soup%20and%20Noodles.png",
  "Masala & Seasoning": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Masala%20&%20Seasoning.png",
  "Bakery, Cakes & Dairy": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Bakery,%20Cakes%20&%20Dairy.png",
  "Snacks, Dry Fruits, Nuts": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Snacks,%20Dry%20Fruits,%20Nuts.png",
  "Oil & Ghee": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Oil%20&%20Ghee.png",
  "Atta, Flours and Sooji": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Atta,%20Flours%20and%20Sooji.png",
  "Rice and Rice Products": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Rice%20and%20Rice%20Products.png",
  "Chocolates and Biscuits": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Chocolates%20and%20Biscuits.png",
  "Snacks & Branded Foods": "",
  "Tea and Coffee": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Tea%20and%20coffee.png",
  "Beauty & Hygiene": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Beauty%20&%20Hygiene.png",
  "Beverages": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Beverages.png",
  "Gourmet & World Foods": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Gourmet%20&%20World%20Foods.png",
  "Frozen Vegetables": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Frozen%20Vegetables.png",
  "Dals and Pulses": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Dals%20and%20Pulses.png",
  "Fruits and Vegetables": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Fruits%20and%20Vegetables.png",
  "Eggs, Meat & Fish": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Eggs,%20Meat%20&%20Fish.png",
  "Sauces, Spreads and Dips": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sauces,%20Spreads%20and%20Dips.png",
  "Cereals and Breakfast": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cereals%20and%20Breakfast.png",
  "Cooking and Baking Needs": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cooking%20and%20Baking%20Needs.png",
  "Salt, Sugar and Jaggery": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Salt,%20Sugar%20and%20Jaggery.png",
  "Ready to Cook and Eat": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Ready%20to%20Cook%20and%20Eat.png",
  "Foodgrains": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Foodgrains.png",
  "Pickles and Chutney": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Pickles%20and%20Chutney.png",
  "Indian Sweets": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Indian%20Sweets.png",
  "Dairy and Cheese": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Dairy%20and%20Cheese.png",
  "Energy and Soft Drinks": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Energy%20and%20Soft%20Drinks.png",
  "Stationery": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Stationery.png",
  "Baby Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Baby%20Care.png",
  "Pet Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Pet%20Care.png",
  "Tinned and Processed Food": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Tinned%20and%20Processed%20Food.png",
  "Kitchen Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Kitchen%20Accessories.png",
  "Water": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Water.png",
  "Cookies": "",
  "Frozen Snacks": "https://d2v00mt5yqy11h.cloudfront.net/categories/grocery.png",
  "Induction Cooktop": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Induction%20Cooktop.png",
  "Cereals & Breakfast": "",
  "Detergents and Dishwash": "",
  "Gift Voucher": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Gift%20Voucher.png",
  "Soft Drink": "",
  "Cleaning Supplies": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cleaning%20Supplies.png",
  "Washing Machine": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Washing%20Machine.png",
  "Audio Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Audio%20Accessories.png",
  "Batteries": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Batteries.png",
  "Hair Care - Shampoo, Oils, Conditioners": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Hair%20Care%20-%20Shampoo,%20Oils,%20Conditioners.png",
  "Tea & Coffee": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Tea%20and%20coffee.png",
  "Clothing Sets": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Clothing%20Sets.png",
  "Tops": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Tops.png",
  "Dresses": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Dresses.png",
  "Shorts": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Shorts.png",
  "Swimwear": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Swimwear.png",
  "Kurtas & Kurta Sets": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Kurtas%20&%20Kurta%20Sets.png",
  "T Shirts": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/T%20Shirts.png",
  "Sweaters": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sweaters.png",
  "Formal Shoes": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Formal%20Shoes.png",
  "Shirts": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Shirts.png",
  "Sarees": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sarees.png",
  "Work & Safety Shoes": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Work%20&%20Safety%20Shoes.png",
  "Handbags": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Handbags.png",
  "Trousers": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Trousers.png",
  "Briefs": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Briefs.png",
  "Belts": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Belts.png",
  "Unstitched Fabrics": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Unstitched%20Fabrics.png",
  "Innerwear & Sleepwear": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/%C2%A0Innerwear%20&%20Sleepwear.png",
  "Backpacks": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Backpacks.png",
  "Rings": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Rings.png",
  "Coordinates": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Coordinates.png",
  "Earrings": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Earrings.png",
  "Jumpsuits": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Jumpsuits.png",
  "Heels": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Heels.png",
  "Necklaces": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Necklaces.png",
  "Pendants": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Pendants.png",
  "Jackets & Coats": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Jackets%20&%20Coats.png",
  "Trolley, Luggage & Suitcases": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Trolley,%20Luggage%20&%20Suitcases.png",
  "Bracelets": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Bracelets.png",
  "Nightwear & Loungewear": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Nightwear%20&%20Loungewear.png",
  "Lehenga Cholis": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Lehenga%20Cholis.png",
  "Kurtis, Tunics": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Kurtis,%20Tunics.png",
  "Jewellery Sets": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Jewellery%20Sets.png",
  "Flip-Flops & Flats": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
  "Sunglasses": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sunglasses.png",
  "Track Pants": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
  "Sandals & Floaters": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sandals%20&%20Floaters.png",
  "Skirts": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Skirts.png",
  "Blazers & Waistcoats": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Blazers%20&%20Waistcoats.png",
  "Suits": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Suits.png",
  "Sweatshirts": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sweatshirts.png",
  "Tights, Leggings & Jeggings": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Tights,%20Leggings%20&%20Jeggings.png",
  "Bangles & Bracelets": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Bangles%20&%20Bracelets.png",
  "Chains": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Chains.png",
  "Sleepwear & Loungewear": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Fashion/InnerwearSleepwear.png",
  "Jeans": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Jeans.png",
  "Lingerie Sets & Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Lingerie%20Sets%20&%20Accessories.png",
  "Ethnic Wear": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Ethnic%20Wear.png",
  "Dupattas & Shawls": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Dupattas%20&%20Shawls.png",
  "Mangalsutra": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mangalsutra.png",
  "Shapewear": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
  "Boots": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Boots.png",
  "Socks": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Socks.png",
  "Anklets": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Anklets.png",
  "Watches": "https://d2v00mt5yqy11h.cloudfront.net/categories/fashion.png",
  "Vests": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Vests.png",
  "Casual Shoes": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Casual%20Shoes.png",
  "Nosepins & Noserings": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Nosepins%20&%20Noserings.png",
  "Toe Rings": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Toe%20Rings.png",
  "Camisoles": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Camisoles.png",
  "Eye Glass Frames": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Eye%20Glass%20Frames.png",
  "Party Wear": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Party%20Wear.png",
  "Brooch": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Brooch.png",
  "Sports Shoes": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sports%20Shoes.png",
  "Eye Glasses": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Eye%20Glasses.png",
  "Gold Coins": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Gold%20Coins.png",
  "kurti": "",
  "Blouses": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Blouses.png",
  "Boxers": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Boxers.png",
  "Stockings": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Stockings.png",
  "T shirt for women": "",
  "Nutrition and Fitness Supplements": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Nutrition%20and%20Fitness%20Supplements.png",
  "Medicated Skin Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Medicated%20Skin%20Care.png",
  "Pain Relief": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Pain%20Relief.png",
  "Sexual Wellness": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sexual%20Wellness.png",
  "Cold and Cough": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cold%20and%20Cough.png",
  "Speciality Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Speciality%20Care.png",
  "Oral Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Oral%20Care.png",
  "Medicated Hair Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Medicated%20Hair%20Care.png",
  "Feminine Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Feminine%20Care.png",
  "Health and Safety": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Health%20and%20Safety.png",
  "Gastric Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Gastric%20Care.png",
  "Health Foods and Drinks": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Health%20Foods%20and%20Drinks.png",
  "Healthcare & Fitness Devices": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Healthcare%20&%20Fitness%20Devices.png",
  "Eye Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Eye%20Care.png",
  "Wound Care and Dressings": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Wound%20Care%20and%20Dressings.png",
  "ENT Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/ENT%20Care.png",
  "Ayurvedic": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Ayurvedic.png",
  "Elder Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Elder%20Care.png",
  "Diabetes Control": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Diabetes%20Control.png",
  "Covid Essentials": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Covid%20Essentials.png",
  "Sanitizers": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sanitizers.png",
  "Orthopaedic Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Orthopaedic%20Care.png",
  "Mental Wellness": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mental%20Wellness.png",
  "Skin Care - Face Cleansers": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Skin%20Care%20-%20Face%20Cleansers.png",
  "Baby Care - Diapers and Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Baby%20Care%20-%20Diapers%20and%20Accessories.png",
  "Bath Soaps and Gels": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Bath%20Soaps%20and%20Gels.png",
  "Skin Care - Lotions, Moisturisers, and Creams": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Skin%20Care%20-%20Lotions,%20Moisturisers,%20and%20Creams.png",
  "Beard Care and Tools": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Beard%20Care%20and%20Tools.png",
  "Makeup - Body": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Makeup%20-%20Body.png",
  "Mobility Aids": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mobility%20Aids.png",
  "Shaving and Grooming": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Shaving%20and%20Grooming.png",
  "Nursing and Feeding": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Nursing%20and%20Feeding.png",
  "Grooming Tools and Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Grooming%20Tools%20and%20Accessories.png",
  "Hand Wash": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Hand%20Wash.png",
  "Breathe Easy": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Breathe%20Easy.png",
  "Fragrance": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Fragrance.png",
  "Makeup - Lips": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Makeup%20-%20Lips.png",
  "Baby Care - Rash Creams": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Baby%20Care%20-%20Rash%20Creams.png",
  "Makeup - Kits and Combos": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Makeup%20-%20Kits%20and%20Combos.png",
  "Makeup - Sets and Kits": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Makeup%20-%20Sets%20and%20Kits.png",
  "Maternity Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Maternity%20Care.png",
  "Personal Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Personal%20Care.png",
  "Surgicals": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Surgicals.png",
  "Unani and Siddha": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Unani%20and%20Siddha.png",
  "Home Decor": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Home%20Decor.png",
  "Kitchen Tools": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Kitchen%20Tools.png",
  "Home Furnishing - Bedding and Linen": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Home%20Furnishing%20-%20Bedding%20and%20Linen.png",
  "Serveware": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Serveware.png",
  "Kitchen Storage and Containers": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Kitchen%20Storage%20and%20Containers.png",
  "Garden & Outdoor": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Garden%20&%20Outdoor.png",
  "Toys and Games": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Toys%20and%20Games.png",
  "Electricals": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Electricals.png",
  "Sports and Fitness Equipment": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Sports%20and%20Fitness%20Equipment.png",
  "Cookware": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cookware.png",
  "Furniture": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Furniture.png",
  "Bathroom and Kitchen fixtures": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Bathroom%20and%20Kitchen%20fixtures.png",
  "Pooja Needs": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Pooja%20Needs.png",
  "Bins and Bathroom": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Bins%20and%20Bathroom.png",
  "Mops, Brushes and Scrubs": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mops,%20Brushes%20and%20Scrubs.png",
  "Fresheners and Repellents": "",
  "Lighting & Electric Fans": "",
  "Home & Decor": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Home%20&%20Decor.png",
  "Closet/Laundry/Shoe Organization": "https://d2v00mt5yqy11h.cloudfront.net/categories/home_decor.png",
  "Kitchen Appliances": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Kitchen%20Appliances.png",
  "Watch Strap Band": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Watch%20Strap%20Band.png",
  "Mobile Cover": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mobile%20Cover.png",
  "Headset": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Headset.png",
  "Mobile Phone": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mobile%20Phone.png",
  "Computer Component": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Computer%20Component.png",
  "Computer Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Computer%20Accessories.png",
  "Speaker": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Speaker.png",
  "Smart Lighting": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Smart%20Lighting.png",
  "Networking Device": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Networking%20Device.png",
  "Laptop Skin": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Laptop%20Skin.png",
  "Laptop Bag": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Laptop%20Bag.png",
  "Remote": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/TV%20Remote.png",
  "Storage Drive": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Storage%20Drive.png",
  "Gaming Controller": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Gaming%20Controller.png",
  "Mobile Screen Guard": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mobile%20Screen%20Guard.png",
  "TV Remote": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/TV%20Remote.png",
  "Printer Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Printer%20Accessories.png",
  "Camera": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Camera.png",
  "Home Safe": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Home%20Safe.png",
  "Mousepad": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mousepad.png",
  "Video Games": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Video%20Games.png",
  "Cable": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cable.png",
  "Desktop and Laptop": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Desktop%20and%20Laptop.png",
  "Earphone": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Earphone.png",
  "Tablet Accessories": "",
  "Headphone": "",
  "Charger": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Charger.png",
  "Adapter": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Adapter.png",
  "Smart Watch": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Smart%20Watch.png",
  "Camcorder": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Camcorder.png",
  "Mouse": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mouse.png",
  "Power Bank": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Power%20Bank.png",
  "Screen Protector": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Screen%20Protector.png",
  "TV Mount": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/TV%20Mount.png",
  "Computer Peripheral": "",
  "Mobile Mount": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Mobile%20Mount.png",
  "Tablet": "https://d2v00mt5yqy11h.cloudfront.net/subCategories/Electronics/Tablet.png",
  "Tripod": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Tripod.png",
  "Camera Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Camera%20Accessories.png",
  "Projector": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Projector.png",
  "Mobile Accessories": "",
  "Video Player Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Video%20Player%20Accessories.png",
  "Cooling Pad": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cooling%20Pad.png",
  "Docking Station": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Docking%20Station.png",
  "Health, Home and Personal Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Health,%20Home%20and%20Personal%20Care.png",
  "Keyboard": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Keyboard.png",
  "Laptop Stand": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Laptop%20Stand.png",
  "Shaver": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Shaver.png",
  "Toaster": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Toaster.png",
  "Trimmer": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Trimmer.png",
  "UPS": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/UPS.png",
  "Hair Oils, Care, and Styling": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Hair%20Oils,%20Care,%20and%20Styling.png",
  "Shampoos and Conditioners": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Shampoos%20and%20Conditioners.png",
  "Makeup - Face": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Makeup%20-%20Face.png",
  "Skin Care - Oils and Serums": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Skin%20Care%20-%20Oils%20and%20Serums.png",
  "Body Care - Cleansers": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Body%20Care%20-%20Cleansers.png",
  "Body Care - Bath Salt and Additives": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Body%20Care%20-%20Bath%20Salt%20and%20Additives.png",
  "Skin Care - Hand and Feet": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Skin%20Care%20-%20Hand%20and%20Feet.png",
  "Body Care - Loofah and Other Tools": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Body%20Care%20-%20Loofah%20and%20Other%20Tools.png",
  "Body Care - Moisturizers": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Body%20Care%20-%20Moisturizers.png",
  "Makeup - Eyes": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Makeup%20-%20Eyes.png",
  "Makeup - Nail Care": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Makeup%20-%20Nail%20Care.png",
  "Baby care ": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Baby%20Care.png",
  "Washing Machine Accessories": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Washing%20Machine%20Accessories.png",
  "Cooking Appliance Accessories ": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Cooking%20Appliance%20Accessories.png",
  "Dehumidifier": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Dehumidifier.png",
  "Juicer": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Juicer.png",
  "Air Heater": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/%C2%A0Air%20Heater.png",
  "Air Purifier": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/%C2%A0Air%20Purifier.png",
  "Blender": "https://d2v00mt5yqy11h.cloudfront.net/sub_categories/Blender.png"
}