export const RetailsErrorCode = {
    '10000': 'Generic bad or invalid request error',
    '10001': 'Cannot verify signature for request',
    '10002': 'Valid city code needs to be passed for search',
    '20000': 'Catalog Item cannot be displayed as it does not meet statutory requirements',
    '20001': 'Cannot verify signature for request',
    '25001': 'Buyer App cannot confirm order as no response from Seller App',
    '30000': 'Generic invalid request error',
    '30001': 'When Seller App is unable to find the provider id sent by the Buyer App',
    '30002': 'When Seller App is unable to find the provider location id sent by the Buyer App',
    '30003': 'When Seller App is unable to find the provider category id sent by the Buyer App',
    '30004': 'When Seller App is unable to find the item id sent by the Buyer App',
    '30005': 'When Seller App is unable to find the category id sent by the Buyer App',
    '30006': 'When Seller App is unable to find the offer id sent by the Buyer App',
    '30007': 'When the Seller App is unable to find the add-on id sent by the Buyer App',
    '30008': 'Pickup location not serviceable by Logistics Provider',
    '30009': 'Dropoff location not serviceable by Logistics Provider',
    '30010': 'Delivery distance exceeds the maximum serviceability distance',
    '30011': 'Delivery Partners not available',
    '30012': 'When the Seller App is unable to find the cancellation reason in cancellation_reason_id',
    '30013': 'When the Seller App finds changes in the order object other than the update_target',
    '30014': 'When the Seller App is unable to find the entity to rate in id',
    '30015': 'When the Seller App receives an invalid value as the rating value in value',
    '30016': 'Cannot verify signature for request',
    '30017': 'Merchant is currently not taking orders',
    '30018': 'Order not found',
    '30019': 'Seller App is unable to confirm the order',
    '30020': 'Seller App cannot confirm order as no response from Buyer App',
    '40000': 'Generic business error',
    '40001': 'When an API endpoint is not implemented by the Seller App as it is not required for their use cases and a Buyer App calls one of these endpoints',
    '40002': 'When the Seller App is unable to select the specified number in order.items[].quantity',
    '40003': 'When the quote sent by the Buyer App is no longer available from the Seller App',
    '40004': 'When the payment object sent by the Buyer App is not supported by the Seller App',
    '40005': 'When the Seller App does not support tracking for the order in order_id',
    '40006': 'When an agent for fulfilment is not available',
    '50000': 'Generic Policy Error',
    '50001': 'When the Seller App is unable to cancel the order due to it\'s cancellation policy',
    '50002': 'When the Seller App is unable to update the order due to it\'s updation policy',
    '50003': 'When the Seller App receives an entity to rate which is not supported',
    '50004': 'When the Seller App receives an object if for which it does not provide support',
    '60001': 'Pickup location not serviceable by Logistics Provider',
    '60002': 'Dropoff location not serviceable by Logistics Provider',
    '60003': 'Delivery distance exceeds the maximum serviceability distance',
    '60004': 'Delivery Partners not available',
    '60005': 'Cannot verify signature for request',
    '60006': 'Invalid request, not compliant with API contract',
    '60007': 'Cancellation not possible because of Logistics Provider policy',
    '65001': 'Logistics Provider is unable to confirm the order',
};